name: Continuously Deploy on Main Branch

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  SERVICE_NAME: greetings-${{ github.event.number }}

jobs:
  cd:
    name: Deploy Main Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: serverless-functions

      - name: 'Deploy Function'
        run: |
          gcloud functions deploy ${SERVICE_NAME} --runtime python310 --trigger-http --allow-unauthenticated --entry-point=greetings

        
